apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mongodb-replicaset
    release: mykrobe
  name: mykrobe-mongodb-replicaset-client
  namespace: mykrobe-dev
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb-replicaset
    release: mykrobe